version: '3'
services:
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - LANG=C.UTF-8
    volumes:
      - $PWD/data/mongo/conf:/etc/mongo/
      - $PWD/data/mongo/db:/var/lib/mongo/
      - $PWD/data/mongo/logs:/var/log/mongo/
      - $PWD/data/mongo/init/init_mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - /etc/localtime:/etc/localtime
      - /usr/share/zoneinfo:/usr/share/zoneinfo/
    command: ["--auth","--config","/etc/mongo/mongod.conf"]
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - net-n7

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - $PWD/data/mysql/conf:/etc/mysql/conf.d/
      - $PWD/data/mysql/db:/var/lib/mysql/
      - $PWD/data/mysql/logs:/var/log/mysql/
      - $PWD/data/mysql/init:/docker-entrypoint-initdb.d/
      - /run/mysqld:/run/mysqld/
      - /usr/share/zoneinfo:/usr/share/zoneinfo/
      - /etc/localtime:/etc/localtime
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    privileged: true
    networks:
      - net-n7

  etcd:
    environment:               
      - ALLOW_NONE_AUTHENTICATION=yes                                   
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379          
      - ETCDCTL_API=3                                            
    volumes:
      - $PWD/data/etcd:/etcd-data/                       
      - /etc/localtime:/etc/localtime/
    image: bitnami/etcd   
    container_name: etcd                
    ports:                   
      - "2379:2379"
      - "2380:2380"
    networks:
      - net-n7

  n7-collector:                                         
    volumes:
      - $PWD/logs/n7-collector:/app/log/                      
      - /etc/localtime:/etc/localtime
    image: eviltomorrow/n7-collector
    container_name: n7-collector                
    ports:                   
      - "5270:5270"
    depends_on:
      - etcd
      - mysql
      - mongo
    networks:
      - net-n7

  n7-email:                                         
    volumes:
      - $PWD/logs/n7-email:/app/log/                      
      - /etc/localtime:/etc/localtime
    image: eviltomorrow/n7-email
    container_name: n7-email                
    ports:                   
      - "5271:5271"
    depends_on:
      - etcd
      - mysql
      - mongo
    networks:
      - net-n7

  n7-repository:                                         
    volumes:
      - $PWD/logs/n7-repository:/app/log/                       
      - /etc/localtime:/etc/localtime
    image: eviltomorrow/n7-repository
    container_name: n7-repository                
    ports:                   
      - "5272:5272"
    depends_on:
      - etcd
      - mysql
      - mongo
    networks:
      - net-n7
      
networks:
  net-n7:
    name: net-n7
    driver: bridge